// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package asyncapi

import (
	"bytes"
	"fmt"
	"go/format"
	"slices"
	"strings"

	"github.com/lemon4ksan/foundation/generic"
)

// ImportConfig configures translation of AsyncAPI specifications into declarative Go contracts.
type ImportConfig struct {
	SpecFile    string
	SpecData    []byte
	PackageName string
	ServiceName string
	OutputFile  string
	MergeMode   MergeMode // "union", "intersect", "diff"
}

// ImportResult captures the outcome of an AsyncAPI import pass.
type ImportResult struct {
	ContractCode  []byte
	ServicesCount int
	MethodsCount  int
	StructsCount  int
}

// Import loads an AsyncAPI specification and translates it into declarative Go contracts.
//
// References:
//   - AsyncAPI 3.1.0 Specification: https://www.asyncapi.com/docs/reference/specification/v3.1.0
//   - AsyncAPI 2.6.0 Specification: https://v2.asyncapi.com/docs/reference/specification/v2.6.0
func Import(cfg ImportConfig) (*ImportResult, error) {
	mode := generic.Coalesce(cfg.MergeMode, MergeModeUnion)

	doc, err := LoadSpecWithMode(cfg.SpecFile, cfg.SpecData, mode)
	if err != nil {
		return nil, fmt.Errorf("vortex/asyncapi: load spec: %w", err)
	}

	code, err := GenerateContract(doc, cfg)
	if err != nil {
		return nil, fmt.Errorf("vortex/asyncapi: generate contract: %w", err)
	}

	return &ImportResult{
		ContractCode:  code,
		ServicesCount: 1,
		MethodsCount:  len(doc.Operations),
		StructsCount:  len(doc.Components.Schemas) + len(doc.Components.Messages),
	}, nil
}

// GenerateContract translates an AsyncAPI document into a clean, declarative aoni Go contract.
//
// References:
//   - AsyncAPI 3.1.0 §Operations Model: https://www.asyncapi.com/docs/reference/specification/v3.1.0#operations-object
//   - AsyncAPI 3.1.0 §Channels Model: https://www.asyncapi.com/docs/reference/specification/v3.1.0#channels-object
//   - RFC 6455 §WebSocket Protocol: https://datatracker.ietf.org/doc/html/rfc6455
//   - RFC 8441 §Bootstrapping WebSockets with HTTP/2: https://datatracker.ietf.org/doc/html/rfc8441
//   - W3C Server-Sent Events: https://www.w3.org/TR/eventsource/
func GenerateContract(doc *Document, cfg ImportConfig) ([]byte, error) {
	pkgName := generic.Coalesce(cfg.PackageName, "api")
	serviceName := resolveServiceName(doc, cfg.ServiceName)

	var bodyBuf bytes.Buffer

	writeServiceContract(&bodyBuf, doc, serviceName)
	writeSubscriptionInterface(&bodyBuf)
	writeSchemas(&bodyBuf, doc)

	return formatSourceFile(pkgName, doc.AsyncAPI, bodyBuf.Bytes())
}

func resolveServiceName(doc *Document, customName string) string {
	if customName != "" {
		return customName
	}

	if doc.Info.Title != "" {
		return sanitizeIdentifier(doc.Info.Title) + "API"
	}

	return "AsyncAPI"
}

func writeServiceContract(buf *bytes.Buffer, doc *Document, serviceName string) {
	buf.WriteString("// @aoni:service\n")

	baseURL, protocol := resolveServerInfo(doc)
	if baseURL != "" {
		fmt.Fprintf(buf, "// @base_url %q\n", baseURL)
	}

	if protocol != "" {
		fmt.Fprintf(buf, "// @protocol %s\n", protocol)
	}

	fmt.Fprintf(buf, "type %s interface {\n", serviceName)

	opKeys := generic.Keys(doc.Operations)
	slices.Sort(opKeys)

	for _, opKey := range opKeys {
		op := doc.Operations[opKey]
		emitOperationMethod(buf, doc, opKey, op)
	}

	buf.WriteString("}\n\n")
}

func writeSubscriptionInterface(buf *bytes.Buffer) {
	buf.WriteString("// Subscription represents an active real-time event listener.\n")
	buf.WriteString("type Subscription interface {\n")
	buf.WriteString("\tUnsubscribe() error\n")
	buf.WriteString("}\n\n")
}

func formatSourceFile(pkgName, asyncAPIVersion string, body []byte) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by vortex from AsyncAPI %s. DO NOT EDIT.\n", asyncAPIVersion)
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n\n")
	buf.WriteString("\t\"github.com/lemon4ksan/aoni\"\n")
	buf.WriteString(")\n\n")

	buf.Write(body)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("vortex/asyncapi: format contract: %w", err)
	}

	return formatted, nil
}

func resolveServerInfo(doc *Document) (baseURL, protocol string) {
	protocol = "ws"

	for _, s := range doc.Servers {
		p := strings.ToLower(s.Protocol)
		if slices.Contains([]string{"wss", "ws", "sse", "socket.io", "socketio"}, p) {
			protocol = generic.Ternary(p == "sse", "http", "ws")
		}

		if s.Host != "" {
			if !strings.Contains(s.Host, "://") {
				baseURL = p + "://" + s.Host
			} else {
				baseURL = s.Host
			}

			if s.Pathname != "" {
				baseURL = strings.TrimSuffix(baseURL, "/") + "/" + strings.TrimPrefix(s.Pathname, "/")
			}

			return baseURL, protocol
		}
	}

	return "", protocol
}

// emitOperationMethod translates an AsyncAPI operation into a typed Go interface method.
//
// References:
//   - AsyncAPI 3.1.0 §Operation Object: https://www.asyncapi.com/docs/reference/specification/v3.1.0#operation-object
//   - AsyncAPI 3.1.0 §Operation Reply Object: https://www.asyncapi.com/docs/reference/specification/v3.1.0#operation-reply-object
func emitOperationMethod(buf *bytes.Buffer, doc *Document, opKey string, op Operation) {
	methodName := generic.Coalesce(sanitizeIdentifier(opKey), "HandleEvent")

	if op.Summary != "" {
		fmt.Fprintf(buf, "\t// %s — %s\n", methodName, op.Summary)
	}

	address := resolveChannelAddress(doc, op)
	cleanAddress := strings.TrimPrefix(address, "/")
	pathParams := extractTemplatePlaceholders(address)
	payloadType := resolvePayloadType(opKey, op)

	// AsyncAPI 3.1.0 §Operation Reply Object -> @rpc pattern
	if op.Reply != nil {
		emitRPCMethod(
			buf,
			opKey,
			methodName,
			cleanAddress,
			payloadType,
			resolveReplyPayloadType(opKey, op),
			pathParams,
		)

		return
	}

	// AsyncAPI 3.1.0 §Action (send = server sends to client -> @event subscription)
	if op.Action == "send" || op.Action == "publish" {
		emitEventSubscriptionMethod(buf, opKey, methodName, cleanAddress, payloadType, pathParams)
		return
	}

	// AsyncAPI 3.1.0 §Action (receive = client sends to server -> @ws:emit)
	emitWsEmitMethod(buf, opKey, methodName, cleanAddress, payloadType, pathParams)
}

func emitRPCMethod(
	buf *bytes.Buffer,
	opKey, methodName, cleanAddress, payloadType, replyType string,
	pathParams []string,
) {
	fmt.Fprintf(buf, "\t// @rpc %q\n", opKey)

	if cleanAddress != "" {
		fmt.Fprintf(buf, "\t// @channel %q\n", cleanAddress)
	}

	params := buildMethodParams("req *"+payloadType, pathParams, true)
	fmt.Fprintf(buf, "\t%s(%s) (*%s, error)\n\n", methodName, strings.Join(params, ", "), replyType)
}

func emitEventSubscriptionMethod(
	buf *bytes.Buffer,
	opKey, methodName, cleanAddress, payloadType string,
	pathParams []string,
) {
	fmt.Fprintf(buf, "\t// @event %q\n", opKey)

	if cleanAddress != "" {
		fmt.Fprintf(buf, "\t// @ws %q\n", cleanAddress)
	}

	handlerSig := fmt.Sprintf("handler func(msg *%s)", payloadType)
	params := buildMethodParams(handlerSig, pathParams, false)
	fmt.Fprintf(buf, "\t%s(%s) (Subscription, error)\n\n", methodName, strings.Join(params, ", "))
}

func emitWsEmitMethod(
	buf *bytes.Buffer,
	opKey, methodName, cleanAddress, payloadType string,
	pathParams []string,
) {
	fmt.Fprintf(buf, "\t// @ws:emit %q\n", opKey)

	if cleanAddress != "" {
		fmt.Fprintf(buf, "\t// @ws %q\n", cleanAddress)
	}

	params := buildMethodParams("req *"+payloadType, pathParams, true)
	fmt.Fprintf(buf, "\t%s(%s) error\n\n", methodName, strings.Join(params, ", "))
}

func buildMethodParams(payloadParam string, pathParams []string, includeMods bool) []string {
	params := make([]string, 0, 3+len(pathParams))

	params = append(params, "ctx context.Context")
	for _, p := range pathParams {
		params = append(params, p+" string")
	}

	params = append(params, payloadParam)
	if includeMods {
		params = append(params, "mods ...aoni.RequestModifier")
	}

	return params
}

func resolveChannelAddress(doc *Document, op Operation) string {
	if op.ChannelRef != "" {
		if ch, ok := doc.Channels[op.ChannelRef]; ok && ch.Address != "" {
			return ch.Address
		}

		return op.ChannelRef
	}

	if op.Channel.Ref != "" {
		refKey := strings.TrimPrefix(op.Channel.Ref, "#/channels/")
		if ch, ok := doc.Channels[refKey]; ok {
			if ch.Address != "" {
				return ch.Address
			}

			return refKey
		}
	}

	return ""
}

func resolvePayloadType(opKey string, op Operation) string {
	for _, mRef := range op.Messages {
		if mRef.Ref != "" {
			return extractTypeNameFromRef(mRef.Ref)
		}
	}

	return sanitizeIdentifier(opKey) + "PayloadDTO"
}

func resolveReplyPayloadType(opKey string, op Operation) string {
	if op.Reply != nil {
		for _, mRef := range op.Reply.Messages {
			if mRef.Ref != "" {
				return extractTypeNameFromRef(mRef.Ref)
			}
		}
	}

	return sanitizeIdentifier(opKey) + "ReplyDTO"
}

func extractTypeNameFromRef(ref string) string {
	refKey := strings.TrimPrefix(ref, "#/components/messages/")

	refKey = strings.TrimPrefix(refKey, "#/channels/")
	if idx := strings.LastIndex(refKey, "/"); idx != -1 {
		refKey = refKey[idx+1:]
	}

	return sanitizeIdentifier(refKey) + "DTO"
}

// writeSchemas translates AsyncAPI Component Schemas and Message Payloads into Go DTO structs.
//
// References:
//   - AsyncAPI 3.1.0 §Schema Object: https://www.asyncapi.com/docs/reference/specification/v3.1.0#schema-object
//   - AsyncAPI 3.1.0 §Message Object: https://www.asyncapi.com/docs/reference/specification/v3.1.0#message-object
func writeSchemas(buf *bytes.Buffer, doc *Document) {
	if doc == nil {
		return
	}

	// 1. Schemas in components
	schemaKeys := generic.Keys(doc.Components.Schemas)
	slices.Sort(schemaKeys)

	for _, schemaName := range schemaKeys {
		schema := doc.Components.Schemas[schemaName]
		structName := sanitizeIdentifier(schemaName) + "DTO"
		fmt.Fprintf(buf, "// %s represents the %s schema.\n", structName, schemaName)
		fmt.Fprintf(buf, "type %s struct {\n", structName)

		propKeys := generic.Keys(schema.Properties)
		slices.Sort(propKeys)

		for _, propName := range propKeys {
			prop := schema.Properties[propName]
			fieldName := sanitizeIdentifier(propName)
			fieldType := mapJSONSchemaType(prop)
			fmt.Fprintf(buf, "\t%s %s `json:\"%s,omitempty\"`\n", fieldName, fieldType, propName)
		}

		buf.WriteString("}\n\n")
	}

	// 2. Messages in components
	msgKeys := generic.Keys(doc.Components.Messages)
	slices.Sort(msgKeys)

	for _, msgName := range msgKeys {
		msg := doc.Components.Messages[msgName]
		structName := sanitizeIdentifier(msgName) + "DTO"
		fmt.Fprintf(buf, "// %s represents the %s event payload.\n", structName, msgName)
		fmt.Fprintf(buf, "type %s struct {\n", structName)

		if pMap, ok := msg.Payload.(map[string]any); ok {
			if props, ok := pMap["properties"].(map[string]any); ok {
				propNames := generic.Keys(props)
				slices.Sort(propNames)

				for _, propName := range propNames {
					propVal := props[propName]
					fieldName := sanitizeIdentifier(propName)
					fieldType := resolveMessageFieldType(propVal)
					fmt.Fprintf(buf, "\t%s %s `json:\"%s,omitempty\"`\n", fieldName, fieldType, propName)
				}
			}
		}

		buf.WriteString("}\n\n")
	}
}

func resolveMessageFieldType(propVal any) string {
	pObj, ok := propVal.(map[string]any)
	if !ok {
		return "any"
	}

	tStr, ok := pObj["type"].(string)
	if !ok {
		return "any"
	}

	fmtStr, _ := pObj["format"].(string)

	return mapScalarTypeWithFormat(tStr, fmtStr)
}

// mapJSONSchemaType translates JSON Schema types to idiomatic Go types.
//
// References:
//   - JSON Schema draft 2020-12 §Validation: https://json-schema.org/draft/2020-12/json-schema-validation.html#name-type
func mapJSONSchemaType(s Schema) string {
	switch s.Type {
	case "string":
		return "string"
	case "integer":
		if s.Format == "int64" {
			return "int64"
		}

		return "int"

	case "number":
		if s.Format == "float" {
			return "float32"
		}

		return "float64"

	case "boolean":
		return "bool"
	case "array":
		if s.Items != nil {
			return "[]" + mapJSONSchemaType(*s.Items)
		}

		return "[]any"

	case "object":
		return "map[string]any"
	default:
		return "any"
	}
}

func mapScalarTypeWithFormat(t, format string) string {
	switch t {
	case "string":
		return "string"
	case "integer":
		if format == "int64" {
			return "int64"
		}

		return "int"

	case "number":
		if format == "float" {
			return "float32"
		}

		return "float64"

	case "boolean":
		return "bool"
	case "array":
		return "[]any"
	case "object":
		return "map[string]any"
	default:
		return "any"
	}
}
