version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/lemon4ksan/vortex)

    gofumpt:
      module-path: github.com/lemon4ksan/vortex
      extra:
        group-params: true

    goimports:
      local-prefixes:
        - github.com/lemon4ksan/vortex

    golines:
      max-len: 120

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - bodyclose
    - nilerr
    - noctx
    - errorlint
    - protogetter
    - gocritic
    - prealloc
    - perfsprint
    - gosec

  settings:
    revive:
      rules:
        - name: exported
          disabled: true

  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - std-error-handling
    rules:
      - linters: [gosec]
        text: "G103:"

      - linters: [gosec]
        text: "G404:"

      - linters: [gosec]
        text: "G115:"

      - linters: [gosec]
        text: "G306:|G301:"

      - linters: [gosec]
        text: "G703:|G706:"

      - linters: [gosec, noctx, bodyclose, errcheck, prealloc]
        path: "_test\\.go"
