// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package emitter_test

import (
	"net/url"
	"strconv"
	"testing"
	"time"

	"github.com/lemon4ksan/foundation/generic"
	"github.com/lemon4ksan/foundation/testing/require"

	"github.com/lemon4ksan/vortex/pkg/emitter"
	"github.com/lemon4ksan/vortex/pkg/parser"
)

// BenchmarkTestDTO is a compiled fixture identical to the code generated by emitter.Emit
// for a comprehensive DTO struct containing all primitive generic.Optional[T] types.
type BenchmarkTestDTO struct {
	StrVal      generic.Optional[string]
	EmptyStr    generic.Optional[string]
	NoneStr     generic.Optional[string]
	IntVal      generic.Optional[int]
	Int64Val    generic.Optional[int64]
	UintVal     generic.Optional[uint]
	Uint64Val   generic.Optional[uint64]
	Float64Val  generic.Optional[float64]
	BoolVal     generic.Optional[bool]
	BoolIntVal  generic.Optional[bool]
	BoolFlagVal generic.Optional[bool]
	TimeVal     generic.Optional[time.Time]
}

func (r *BenchmarkTestDTO) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if optVal, ok := r.StrVal.Value(); ok {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "str="...)
		if optVal != "" {
			dst = appendQueryEscape(dst, optVal)
		}
	}
	if optVal, ok := r.EmptyStr.Value(); ok {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "empty_str="...)
		if optVal != "" {
			dst = appendQueryEscape(dst, optVal)
		}
	}
	if optVal, ok := r.NoneStr.Value(); ok {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "none_str="...)
		if optVal != "" {
			dst = appendQueryEscape(dst, optVal)
		}
	}
	if optVal, ok := r.IntVal.Value(); ok {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "i="...)
		dst = strconv.AppendInt(dst, int64(optVal), 10)
	}
	if optVal, ok := r.Int64Val.Value(); ok {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "i64="...)
		dst = strconv.AppendInt(dst, optVal, 10)
	}
	if optVal, ok := r.UintVal.Value(); ok {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "u="...)
		dst = strconv.AppendUint(dst, uint64(optVal), 10)
	}
	if optVal, ok := r.Uint64Val.Value(); ok {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "u64="...)
		dst = strconv.AppendUint(dst, optVal, 10)
	}
	if optVal, ok := r.Float64Val.Value(); ok {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "f64="...)
		dst = strconv.AppendFloat(dst, optVal, 'f', -1, 64)
	}
	if optVal, ok := r.BoolVal.Value(); ok {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		if optVal {
			dst = append(dst, "b=true"...)
		} else {
			dst = append(dst, "b=false"...)
		}
	}
	if optVal, ok := r.BoolIntVal.Value(); ok {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		if optVal {
			dst = append(dst, "b_int=1"...)
		} else {
			dst = append(dst, "b_int=0"...)
		}
	}
	if optVal, ok := r.BoolFlagVal.Value(); ok {
		if optVal {
			if len(dst) > 0 {
				dst = append(dst, '&')
			}
			dst = append(dst, "b_flag"...)
		}
	}
	if optVal, ok := r.TimeVal.Value(); ok && !optVal.IsZero() {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "ts="...)
		var timeBuf [32]byte
		timeBytes := optVal.AppendFormat(timeBuf[:0], time.RFC3339)
		for _, c := range timeBytes {
			switch c {
			case ':':
				dst = append(dst, "%3A"...)
			case '+':
				dst = append(dst, "%2B"...)
			default:
				dst = append(dst, c)
			}
		}
	}

	return dst
}

func (r *BenchmarkTestDTO) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

func (r *BenchmarkTestDTO) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}

	if optVal, ok := r.StrVal.Value(); ok {
		vals.Set("str", optVal)
	}
	if optVal, ok := r.EmptyStr.Value(); ok {
		vals.Set("empty_str", optVal)
	}
	if optVal, ok := r.NoneStr.Value(); ok {
		vals.Set("none_str", optVal)
	}
	if optVal, ok := r.IntVal.Value(); ok {
		vals.Set("i", strconv.FormatInt(int64(optVal), 10))
	}
	if optVal, ok := r.Int64Val.Value(); ok {
		vals.Set("i64", strconv.FormatInt(optVal, 10))
	}
	if optVal, ok := r.UintVal.Value(); ok {
		vals.Set("u", strconv.FormatUint(uint64(optVal), 10))
	}
	if optVal, ok := r.Uint64Val.Value(); ok {
		vals.Set("u64", strconv.FormatUint(optVal, 10))
	}
	if optVal, ok := r.Float64Val.Value(); ok {
		vals.Set("f64", strconv.FormatFloat(optVal, 'f', -1, 64))
	}
	if optVal, ok := r.BoolVal.Value(); ok {
		if optVal {
			vals.Set("b", "true")
		} else {
			vals.Set("b", "false")
		}
	}
	if optVal, ok := r.BoolIntVal.Value(); ok {
		if optVal {
			vals.Set("b_int", "1")
		} else {
			vals.Set("b_int", "0")
		}
	}
	if optVal, ok := r.TimeVal.Value(); ok && !optVal.IsZero() {
		vals.Set("ts", optVal.Format(time.RFC3339))
	}
}

func appendQueryEscape(dst []byte, s string) []byte {
	const hexUpper = "0123456789ABCDEF"
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case ('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z') || ('0' <= c && c <= '9') ||
			c == '-' || c == '_' || c == '.' || c == '~':
			dst = append(dst, c)
		case c == ' ':
			dst = append(dst, '+')
		default:
			dst = append(dst, '%', hexUpper[c>>4], hexUpper[c&15])
		}
	}
	return dst
}

var benchmarkFixedTime = time.Date(2026, 9, 22, 14, 30, 0, 0, time.UTC)

func newFullBenchmarkDTO() *BenchmarkTestDTO {
	return &BenchmarkTestDTO{
		StrVal:      generic.Some("hello world"),
		EmptyStr:    generic.Some(""),
		NoneStr:     generic.None[string](),
		IntVal:      generic.Some(42),
		Int64Val:    generic.Some(int64(-64000000000)),
		UintVal:     generic.Some(uint(100)),
		Uint64Val:   generic.Some(uint64(18446744073709551615)),
		Float64Val:  generic.Some(3.1415926535),
		BoolVal:     generic.Some(true),
		BoolIntVal:  generic.Some(true),
		BoolFlagVal: generic.Some(true),
		TimeVal:     generic.Some(benchmarkFixedTime),
	}
}

func TestDTO_FixtureMatchesEmitterCodegen(t *testing.T) {
	src := `package testdto

import (
	"time"
	"github.com/lemon4ksan/foundation/generic"
)

// @aoni:dto
type BenchmarkTestDTO struct {
	StrVal      generic.Optional[string]    ` + "`query:\"str\"`" + `
	EmptyStr    generic.Optional[string]    ` + "`query:\"empty_str\"`" + `
	NoneStr     generic.Optional[string]    ` + "`query:\"none_str\"`" + `
	IntVal      generic.Optional[int]       ` + "`query:\"i\"`" + `
	Int64Val    generic.Optional[int64]     ` + "`query:\"i64\"`" + `
	UintVal     generic.Optional[uint]      ` + "`query:\"u\"`" + `
	Uint64Val   generic.Optional[uint64]    ` + "`query:\"u64\"`" + `
	Float64Val  generic.Optional[float64]   ` + "`query:\"f64\"`" + `
	BoolVal     generic.Optional[bool]      ` + "`query:\"b\"`" + `
	// @format bool_int
	BoolIntVal  generic.Optional[bool]      ` + "`query:\"b_int\"`" + `
	// @format flag
	BoolFlagVal generic.Optional[bool]      ` + "`query:\"b_flag\"`" + `
	TimeVal     generic.Optional[time.Time] ` + "`query:\"ts\"`" + `
}
`
	p := parser.NewParser()
	root, err := p.ParseSource("fixture.go", []byte(src))
	require.NoError(t, err)

	genBytes, err := emitter.Emit(root)
	require.NoError(t, err)
	code := string(genBytes)

	require.Contains(t, code, "func (r *BenchmarkTestDTO) AppendFormData(dst []byte) []byte")
	require.Contains(t, code, "func (r *BenchmarkTestDTO) AppendQuery(dst []byte) []byte")
	require.Contains(t, code, "func (r *BenchmarkTestDTO) EncodeValues(vals url.Values)")
}
