// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package emitter generates high-performance, zero-allocation Go client facades from Vortex AST RootIR contracts.
package emitter

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"path/filepath"

	"github.com/lemon4ksan/vortex/pkg/ir"
	"github.com/lemon4ksan/vortex/pkg/version"
)

// Emit compiles RootIR into formatted Go source code.
func Emit(root *ir.RootIR) ([]byte, error) {
	if root == nil {
		return nil, errors.New("root IR cannot be nil")
	}

	var bodyBuf bytes.Buffer

	tracker := NewImportTracker()

	// 1. Services (HTTP / RPC / Socket facades, constructors, methods)
	for _, svc := range root.Services {
		emitHTTPService(&bodyBuf, tracker, root, svc)
	}

	// 2. Multi-Status Unions
	for _, u := range root.Unions {
		emitUnion(&bodyBuf, tracker, u)
	}

	// 3. Bitpack Structs
	for _, b := range root.Bitpacks {
		emitBitpack(&bodyBuf, tracker, b)
	}

	// 4. DTO Structs
	for _, s := range root.Structs {
		emitStructDTO(&bodyBuf, tracker, s)
	}

	// 5. JSON Array Tuples
	for _, t := range root.Tuples {
		emitTuple(&bodyBuf, tracker, t)
	}

	bodyCode := bodyBuf.String()
	tracker.RegisterRootImports(root, bodyCode)

	var fileBuf bytes.Buffer
	fileBuf.WriteString("// Code generated by vortex. DO NOT EDIT.\n")
	fileBuf.WriteString("// versions:\n")
	fmt.Fprintf(&fileBuf, "// \tvortex %s\n", version.Current)

	if root.SourceFile != "" {
		fmt.Fprintf(&fileBuf, "// source: %s\n", filepath.Base(root.SourceFile))
	}

	fileBuf.WriteString("\n")

	pkgName := root.PackageName
	if pkgName == "" {
		pkgName = "api"
	}

	fmt.Fprintf(&fileBuf, "package %s\n\n", pkgName)

	tracker.Render(&fileBuf)
	fileBuf.WriteString(bodyCode)

	formatted, err := format.Source(fileBuf.Bytes())
	if err != nil {
		return fileBuf.Bytes(), fmt.Errorf("format source error: %w\nGenerated code:\n%s", err, fileBuf.String())
	}

	return formatted, nil
}
