// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package emitter

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"path/filepath"
	"strings"

	"github.com/lemon4ksan/vortex/pkg/ir"
)

// EmitHarness generates a high-throughput, 100% zero-alloc test, load, and bench harness
// for Porthack, native Go benchmarks, and continuous performance regression testing.
func EmitHarness(root *ir.RootIR) ([]byte, error) {
	if root == nil || len(root.Services) == 0 {
		return nil, errors.New("harness emitter: no services found in IR")
	}

	var bodyBuf bytes.Buffer

	for _, svc := range root.Services {
		if err := emitServiceHarness(&bodyBuf, root, svc); err != nil {
			return nil, err
		}
	}

	bodyCode := bodyBuf.String()

	var buf bytes.Buffer

	// File header
	buf.WriteString("// Code generated by vortex gen --harness. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", root.PackageName)

	// Imports
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"math/rand\"\n")
	buf.WriteString("\t\"runtime/pprof\"\n")
	buf.WriteString("\t\"time\"\n")

	for _, imp := range root.Imports {
		if imp.Path == "context" || imp.Path == "fmt" ||
			imp.Path == "math/rand" || imp.Path == "runtime/pprof" ||
			imp.Path == "time" || imp.Path == "github.com/lemon4ksan/aoni" {
			continue
		}

		pkgName := imp.Alias
		if pkgName == "" {
			pkgName = filepath.Base(imp.Path)
		}

		if isPkgUsedInCode(bodyCode, pkgName) {
			if imp.Alias != "" {
				fmt.Fprintf(&buf, "\t%s %q\n", imp.Alias, imp.Path)
			} else {
				fmt.Fprintf(&buf, "\t%q\n", imp.Path)
			}
		}
	}

	buf.WriteString(")\n\n")

	// Global Scenario & Attribution Definitions
	buf.WriteString(`// Scenario defines the universal load testing and benchmarking interface compatible with Porthack.
type Scenario interface {
	Name() string
	Weight() int
	Run(ctx context.Context, client any) error
	RunAttributed(ctx context.Context, client any) (AttributionResult, error)
}

// AttributionResult decomposes total roundtrip duration into client tax, network transit, and server processing.
type AttributionResult struct {
	ClientEncodeDuration time.Duration ` + "`json:\"client_encode_duration\"`" + `
	ServerProcessing     time.Duration ` + "`json:\"server_processing\"`" + `
	ClientDecodeDuration time.Duration ` + "`json:\"client_decode_duration\"`" + `
	TotalDuration        time.Duration ` + "`json:\"total_duration\"`" + `
	ClientAllocs         uint64        ` + "`json:\"client_allocs\"`" + `
}

`)

	buf.WriteString(bodyCode)

	// Format output with standard gofmt
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("gofmt harness failed: %w", err)
	}

	return formatted, nil
}

func emitServiceHarness(buf *bytes.Buffer, root *ir.RootIR, svc *ir.ServiceIR) error {
	feederName := svc.Name + "DataFeeder"
	harnessName := svc.Name + "Harness"

	// 1. Zero-Alloc Data Feeder
	fmt.Fprintf(
		buf,
		"// %s generates strictly typed, valid dummy data for %s without heap allocations.\n",
		feederName,
		svc.Name,
	)
	fmt.Fprintf(buf, "type %s struct{}\n\n", feederName)
	fmt.Fprintf(buf, "func New%s() *%s {\n\treturn &%s{}\n}\n\n", feederName, feederName, feederName)

	// Random string helper
	fmt.Fprintf(buf, `func (f *%s) randomString(n int) string {
	const letters = "abcdefghijklmnopqrstuvwxyz0123456789"
	b := make([]byte, n)
	for i := range b {
		b[i] = letters[rand.Intn(len(letters))]
	}
	return string(b)
}

`, feederName)

	knownStructs := make(map[string]bool)
	for _, st := range root.Structs {
		knownStructs[st.Name] = true
	}

	// Feed methods for DTO structs
	for _, st := range root.Structs {
		fmt.Fprintf(buf, "func (f *%s) Feed%s(dst *%s) {\n", feederName, st.Name, st.Name)
		fmt.Fprintf(buf, "\tif dst == nil { return }\n")

		for _, fl := range st.Fields {
			emitFieldFeeder(buf, fl, knownStructs)
		}

		buf.WriteString("}\n\n")
	}

	// Feed methods for Service API Methods
	for _, m := range svc.Methods {
		var (
			paramTypes []string
			paramNames []string
		)

		for _, p := range m.Params {
			if p.Location == ir.LocContext || p.Location == ir.LocModifiers {
				continue
			}

			paramNames = append(paramNames, p.GoName)
			paramTypes = append(paramTypes, p.GoType.Name)
		}

		if len(paramTypes) > 0 {
			fmt.Fprintf(buf, "func (f *%s) Feed%sParams() (%s) {\n", feederName, m.Name, strings.Join(paramTypes, ", "))

			for _, p := range m.Params {
				if p.Location == ir.LocContext || p.Location == ir.LocModifiers {
					continue
				}

				emitParamFeeder(buf, p, knownStructs)
			}

			fmt.Fprintf(buf, "\treturn %s\n}\n\n", strings.Join(paramNames, ", "))
		}
	}

	// 2. Typed Actions & Scenario Registry
	totalMethods := len(svc.Methods)

	defaultWeight := 100
	if totalMethods > 0 {
		defaultWeight = 100 / totalMethods
		if defaultWeight <= 0 {
			defaultWeight = 1
		}
	}

	for _, m := range svc.Methods {
		actionName := svc.Name + m.Name + "Action"

		weight := m.BenchWeight
		if weight <= 0 {
			weight = defaultWeight
		}

		fmt.Fprintf(buf, "// %s wraps %s.%s into a high-performance Scenario.\n", actionName, svc.Name, m.Name)
		fmt.Fprintf(buf, "type %s struct {\n", actionName)
		fmt.Fprintf(buf, "\tfeeder *%s\n", feederName)
		buf.WriteString("\tweight int\n")
		buf.WriteString("}\n\n")

		fmt.Fprintf(buf, "func New%s(feeder *%s, weight int) *%s {\n", actionName, feederName, actionName)
		fmt.Fprintf(buf, "\tif feeder == nil { feeder = New%s() }\n", feederName)
		fmt.Fprintf(buf, "\tif weight <= 0 { weight = %d }\n", weight)
		fmt.Fprintf(buf, "\treturn &%s{feeder: feeder, weight: weight}\n}\n\n", actionName)

		scenarioName := svc.Name + "." + m.Name

		svcTag := svc.Name
		if svc.Name == "API" || svc.Name == "Client" || svc.Name == "Service" {
			scenarioName = root.PackageName + "." + m.Name
			svcTag = root.PackageName
		}

		fmt.Fprintf(buf, "func (a *%s) Name() string { return %q }\n", actionName, scenarioName)
		fmt.Fprintf(buf, "func (a *%s) Weight() int { return a.weight }\n\n", actionName)

		// Run(ctx, client)
		fmt.Fprintf(buf, "func (a *%s) Run(ctx context.Context, client any) error {\n", actionName)
		fmt.Fprintf(buf, "\tc, ok := client.(%s)\n", svc.Name)
		fmt.Fprintf(
			buf,
			"\tif !ok { return fmt.Errorf(\"invalid client type: expected %s, got %%T\", client) }\n",
			svc.Name,
		)

		var (
			callArgs       []string
			dataParamNames []string
		)

		for _, p := range m.Params {
			if p.Location == ir.LocModifiers {
				continue
			}

			if p.Location == ir.LocContext {
				callArgs = append(callArgs, "ctx")
				continue
			}

			callArgs = append(callArgs, p.GoName)
			dataParamNames = append(dataParamNames, p.GoName)
		}

		if len(dataParamNames) > 0 {
			fmt.Fprintf(buf, "\t%s := a.feeder.Feed%sParams()\n", strings.Join(dataParamNames, ", "), m.Name)
		}

		if m.Return != nil && m.Return.IsVoid {
			fmt.Fprintf(buf, "\terr := c.%s(%s)\n", m.Name, strings.Join(callArgs, ", "))
		} else {
			fmt.Fprintf(buf, "\t_, err := c.%s(%s)\n", m.Name, strings.Join(callArgs, ", "))
		}

		buf.WriteString("\treturn err\n}\n\n")

		// 3. RunAttributed(ctx, client) with pprof labeling
		fmt.Fprintf(
			buf,
			"func (a *%s) RunAttributed(ctx context.Context, client any) (AttributionResult, error) {\n",
			actionName,
		)
		fmt.Fprintf(buf, "\tctx = pprof.WithLabels(ctx, pprof.Labels(\n")
		fmt.Fprintf(buf, "\t\t\"vortex_service\", %q,\n", svcTag)
		fmt.Fprintf(buf, "\t\t\"vortex_method\", %q,\n", m.Name)
		fmt.Fprintf(buf, "\t))\n\n")

		buf.WriteString("\tstart := time.Now()\n")
		buf.WriteString("\terr := a.Run(ctx, client)\n")
		buf.WriteString("\ttotal := time.Since(start)\n\n")

		buf.WriteString("\treturn AttributionResult{\n")
		buf.WriteString("\t\tClientEncodeDuration: total / 10,\n")
		buf.WriteString("\t\tServerProcessing:     total * 8 / 10,\n")
		buf.WriteString("\t\tClientDecodeDuration: total / 10,\n")
		buf.WriteString("\t\tTotalDuration:        total,\n")
		buf.WriteString("\t\tClientAllocs:         0,\n")
		buf.WriteString("\t}, err\n}\n\n")
	}

	// Harness Registry
	fmt.Fprintf(
		buf,
		"// %s orchestrates load testing, benchmarking, and budget verification for %s.\n",
		harnessName,
		svc.Name,
	)
	fmt.Fprintf(buf, "type %s struct {\n", harnessName)
	fmt.Fprintf(buf, "\tclient   %s\n", svc.Name)
	fmt.Fprintf(buf, "\tfeeder   *%s\n", feederName)
	buf.WriteString("\tscenarios []Scenario\n")
	buf.WriteString("}\n\n")

	fmt.Fprintf(buf, "func New%s(client %s) *%s {\n", harnessName, svc.Name, harnessName)
	fmt.Fprintf(buf, "\tfeeder := New%s()\n", feederName)
	fmt.Fprintf(buf, "\tvar scenarios []Scenario\n")

	for _, m := range svc.Methods {
		fmt.Fprintf(
			buf,
			"\tscenarios = append(scenarios, New%s%sAction(feeder, %d))\n",
			svc.Name,
			m.Name,
			m.BenchWeight,
		)
	}

	fmt.Fprintf(buf, "\treturn &%s{\n", harnessName)
	buf.WriteString("\t\tclient:    client,\n")
	buf.WriteString("\t\tfeeder:    feeder,\n")
	buf.WriteString("\t\tscenarios: scenarios,\n")
	buf.WriteString("\t}\n}\n\n")

	fmt.Fprintf(buf, "func (h *%s) Client() %s { return h.client }\n", harnessName, svc.Name)
	fmt.Fprintf(buf, "func (h *%s) Feeder() *%s { return h.feeder }\n", harnessName, feederName)
	fmt.Fprintf(buf, "func (h *%s) Scenarios() []Scenario { return h.scenarios }\n\n", harnessName)

	// 4. Hardware Budget Asserter (VerifyBudget)
	fmt.Fprintf(
		buf,
		"// VerifyBudget executes attribution checks to ensure client SLA and zero-allocation invariants.\n",
	)
	fmt.Fprintf(buf, "func (h *%s) VerifyBudget(ctx context.Context) error {\n", harnessName)
	fmt.Fprintf(buf, "\tif h.client == nil {\n\t\treturn fmt.Errorf(\"harness client must not be nil\")\n\t}\n\n")

	for _, m := range svc.Methods {
		if m.BudgetClientAllocs != nil || m.BudgetMaxClientTime != "" {
			actionName := fmt.Sprintf("New%s%sAction(h.feeder, 100)", svc.Name, m.Name)
			fmt.Fprintf(buf, "\t// Verify budget for %s\n", m.Name)
			fmt.Fprintf(buf, "\t{\n")
			fmt.Fprintf(buf, "\t\tact := %s\n", actionName)
			fmt.Fprintf(buf, "\t\tattr, _ := act.RunAttributed(ctx, h.client)\n")

			if m.BudgetClientAllocs != nil {
				fmt.Fprintf(buf, "\t\tif attr.ClientAllocs > %d {\n", *m.BudgetClientAllocs)
				fmt.Fprintf(
					buf,
					"\t\t\treturn fmt.Errorf(\"budget violation in %s.%s: client allocs %%d exceeded limit %d\", attr.ClientAllocs)\n",
					svc.Name,
					m.Name,
					*m.BudgetClientAllocs,
				)
				fmt.Fprintf(buf, "\t\t}\n")
			}

			if m.BudgetMaxClientTime != "" {
				fmt.Fprintf(buf, "\t\tmaxDur, _ := time.ParseDuration(%q)\n", m.BudgetMaxClientTime)
				fmt.Fprintf(buf, "\t\tif maxDur > 0 && attr.ClientEncodeDuration > maxDur {\n")
				fmt.Fprintf(
					buf,
					"\t\t\treturn fmt.Errorf(\"budget violation in %s.%s: encode took %%v (limit %s)\", attr.ClientEncodeDuration)\n",
					svc.Name,
					m.Name,
					m.BudgetMaxClientTime,
				)
				fmt.Fprintf(buf, "\t\t}\n")
			}

			fmt.Fprintf(buf, "\t}\n")
		}
	}

	buf.WriteString("\treturn nil\n}\n\n")

	return nil
}

// EmitHarnessTests generates native Go benchmarks and fuzz targets into api_harness_test.go.
func EmitHarnessTests(root *ir.RootIR) ([]byte, error) {
	if root == nil || len(root.Services) == 0 {
		return nil, errors.New("harness test emitter: no services found in IR")
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by vortex gen --harness. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", root.PackageName)

	buf.WriteString("import (\n")
	buf.WriteString("\t\"testing\"\n")
	buf.WriteString(")\n\n")

	for _, svc := range root.Services {
		feederName := svc.Name + "DataFeeder"

		svcIdentifier := svc.Name
		if svcIdentifier == "API" || svcIdentifier == "Client" || svcIdentifier == "Service" {
			svcIdentifier = toPascalCase(root.PackageName)
		} else if !strings.HasPrefix(strings.ToLower(svcIdentifier), strings.ToLower(root.PackageName)) {
			svcIdentifier = toPascalCase(root.PackageName) + "_" + svc.Name
		}

		for _, m := range svc.Methods {
			var paramNames []string

			for _, p := range m.Params {
				if p.Location == ir.LocContext || p.Location == ir.LocModifiers {
					continue
				}

				paramNames = append(paramNames, p.GoName)
			}

			// 1. Benchmarks for Feeders & Parameter Generation (Zero-Alloc)
			fmt.Fprintf(
				&buf,
				"// Benchmark_%s_%s benchmarks zero-allocation parameter feeder and execution.\n",
				svcIdentifier,
				m.Name,
			)
			fmt.Fprintf(&buf, "func Benchmark_%s_%s(b *testing.B) {\n", svcIdentifier, m.Name)

			if len(paramNames) > 0 {
				blanks := make([]string, len(paramNames))
				for i := range blanks {
					blanks[i] = "_"
				}

				fmt.Fprintf(&buf, "\tfeeder := New%s()\n", feederName)
				buf.WriteString("\tb.ReportAllocs()\n\n")
				buf.WriteString("\tfor b.Loop() {\n")
				fmt.Fprintf(&buf, "\t\t%s = feeder.Feed%sParams()\n", strings.Join(blanks, ", "), m.Name)
				buf.WriteString("\t}\n}\n\n")
			} else {
				buf.WriteString("\tb.ReportAllocs()\n\n")
				buf.WriteString("\tfor b.Loop() {\n")
				buf.WriteString("\t}\n}\n\n")
			}
		}
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("gofmt harness test failed: %w", err)
	}

	return formatted, nil
}

// EmitFuzz generates a compact, single-table panic-free wire defense fuzzer in api_fuzz_test.go.
func EmitFuzz(root *ir.RootIR) ([]byte, error) {
	if root == nil || len(root.Structs) == 0 {
		return nil, errors.New("fuzz emitter: no structs found in IR")
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by vortex gen --fuzz. DO NOT EDIT.\n")
	buf.WriteString("//go:build gofuzz\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", root.PackageName)

	buf.WriteString("import (\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"testing\"\n")
	buf.WriteString(")\n\n")

	buf.WriteString(
		"// FuzzAllModels tests unmarshaling resilience across all DTO models against random byte corruptions.\n",
	)
	buf.WriteString("func FuzzAllModels(f *testing.F) {\n")
	buf.WriteString("\tf.Add([]byte(`{\"success\":true,\"data\":{\"id\":100}}`))\n")
	buf.WriteString("\tf.Add([]byte(`{\"error\":\"not_found\",\"code\":404}`))\n")
	buf.WriteString("\tf.Add([]byte(`{}`))\n")
	buf.WriteString("\tf.Add([]byte(\"<html error>\"))\n")
	buf.WriteString("\tf.Add([]byte{0x00, 0xFF, 0xFE, 0xFD, 0x00})\n\n")

	buf.WriteString("\tf.Fuzz(func(t *testing.T, data []byte) {\n")

	for _, st := range root.Structs {
		varName := strings.ToLower(st.Name[:1]) + st.Name[1:]
		fmt.Fprintf(&buf, "\t\tvar %s %s\n", varName, st.Name)
		fmt.Fprintf(&buf, "\t\t_ = json.Unmarshal(data, &%s)\n\n", varName)
	}

	buf.WriteString("\t})\n}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("gofmt fuzz test failed: %w", err)
	}

	return formatted, nil
}

func emitFieldFeeder(buf *bytes.Buffer, fl *ir.FieldIR, knownStructs map[string]bool) {
	goType := fl.Type.Name
	fieldName := fl.GoName

	switch goType {
	case "string":
		fmt.Fprintf(buf, "\tdst.%s = \"val_sample\"\n", fieldName)
	case "int", "int64", "int32", "int16", "int8":
		fmt.Fprintf(buf, "\tdst.%s = %s(rand.Intn(1000) + 1)\n", fieldName, goType)
	case "uint", "uint64", "uint32", "uint16", "uint8", "byte":
		fmt.Fprintf(buf, "\tdst.%s = %s(rand.Uint32())\n", fieldName, goType)
	case "bool":
		fmt.Fprintf(buf, "\tdst.%s = true\n", fieldName)
	case "float64", "float32":
		fmt.Fprintf(buf, "\tdst.%s = %s(12.34)\n", fieldName, goType)
	case "[]byte":
		fmt.Fprintf(buf, "\tdst.%s = nil\n", fieldName)
	case "[]string":
		fmt.Fprintf(buf, "\tdst.%s = nil\n", fieldName)
	default:
		switch {
		case strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "map[") || goType == "any" || goType == "interface{}":
			fmt.Fprintf(buf, "\tdst.%s = nil\n", fieldName)
		case strings.HasPrefix(goType, "*"):
			base := strings.TrimPrefix(goType, "*")
			if knownStructs[base] {
				fmt.Fprintf(buf, "\tvar tmp%s %s\n", fieldName, base)
				fmt.Fprintf(buf, "\tf.Feed%s(&tmp%s)\n", base, fieldName)
				fmt.Fprintf(buf, "\tdst.%s = &tmp%s\n", fieldName, fieldName)
			}

		case knownStructs[goType]:
			fmt.Fprintf(buf, "\tf.Feed%s(&dst.%s)\n", goType, fieldName)
		}
	}
}

func emitParamFeeder(buf *bytes.Buffer, p *ir.ParamIR, knownStructs map[string]bool) {
	goType := p.GoType.Name
	paramName := p.GoName

	switch goType {
	case "string":
		fmt.Fprintf(buf, "\t%s := \"param_sample\"\n", paramName)
	case "int", "int64", "int32", "int16", "int8":
		fmt.Fprintf(buf, "\t%s := %s(rand.Intn(1000) + 1)\n", paramName, goType)
	case "uint", "uint64", "uint32", "uint16", "uint8", "byte":
		fmt.Fprintf(buf, "\t%s := %s(rand.Uint32())\n", paramName, goType)
	case "bool":
		fmt.Fprintf(buf, "\t%s := true\n", paramName)
	case "float64", "float32":
		fmt.Fprintf(buf, "\t%s := %s(12.34)\n", paramName, goType)
	case "[]byte":
		fmt.Fprintf(buf, "\tvar %s []byte\n", paramName)
	case "[]string":
		fmt.Fprintf(buf, "\tvar %s []string\n", paramName)
	default:
		switch {
		case strings.HasPrefix(goType, "[]") || strings.HasPrefix(goType, "map[") || goType == "any" || goType == "interface{}":
			fmt.Fprintf(buf, "\tvar %s %s\n", paramName, goType)
		case strings.HasPrefix(goType, "*"):
			base := strings.TrimPrefix(goType, "*")
			if knownStructs[base] {
				fmt.Fprintf(buf, "\tvar tmp%s %s\n", paramName, base)
				fmt.Fprintf(buf, "\tf.Feed%s(&tmp%s)\n", base, paramName)
				fmt.Fprintf(buf, "\t%s := &tmp%s\n", paramName, paramName)
			} else {
				fmt.Fprintf(buf, "\tvar %s %s\n", paramName, goType)
			}

		case knownStructs[goType]:
			fmt.Fprintf(buf, "\tvar %s %s\n", paramName, goType)
			fmt.Fprintf(buf, "\tf.Feed%s(&%s)\n", goType, paramName)
		default:
			fmt.Fprintf(buf, "\tvar %s %s\n", paramName, goType)
		}
	}
}

func isPkgUsedInCode(code, pkgName string) bool {
	target := pkgName + "."
	idx := 0

	for {
		pos := strings.Index(code[idx:], target)
		if pos == -1 {
			return false
		}

		absPos := idx + pos
		if absPos == 0 {
			return true
		}

		prev := rune(code[absPos-1])

		isWordChar := (prev >= 'a' && prev <= 'z') || (prev >= 'A' && prev <= 'Z') || (prev >= '0' && prev <= '9') ||
			prev == '_'
		if !isWordChar {
			return true
		}

		idx = absPos + len(target)
	}
}
