// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package emitter

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"path/filepath"
	"strings"

	"github.com/lemon4ksan/vortex/pkg/ir"
)

// EmitMock generates a zero-dependency in-memory virtual test server for unit and integration testing.
func EmitMock(root *ir.RootIR) ([]byte, error) {
	if root == nil || len(root.Services) == 0 {
		return nil, errors.New("mock emitter: no services found in IR")
	}

	var bodyBuf bytes.Buffer

	for _, svc := range root.Services {
		if err := emitServiceMock(&bodyBuf, svc); err != nil {
			return nil, err
		}
	}

	bodyCode := bodyBuf.String()

	var buf bytes.Buffer

	// File header
	buf.WriteString("// Code generated by vortex mock. DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", root.PackageName)

	// Imports
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"encoding/json\"\n")
	buf.WriteString("\t\"fmt\"\n")
	buf.WriteString("\t\"net/http\"\n")
	buf.WriteString("\t\"net/http/httptest\"\n")

	if strings.Contains(bodyCode, "strconv.") {
		buf.WriteString("\t\"strconv\"\n")
	}

	if strings.Contains(bodyCode, "strings.") {
		buf.WriteString("\t\"strings\"\n")
	}

	buf.WriteString("\t\"sync\"\n")

	if strings.Contains(bodyCode, "testing.") {
		buf.WriteString("\t\"testing\"\n")
	}

	if strings.Contains(bodyCode, "time.") {
		buf.WriteString("\t\"time\"\n")
	}

	buf.WriteString("\n")
	buf.WriteString("\t\"github.com/lemon4ksan/aoni\"\n")

	if strings.Contains(bodyCode, "fast.") {
		buf.WriteString("\t\"github.com/lemon4ksan/aoni/fast\"\n")
	}

	buf.WriteString("\t\"github.com/lemon4ksan/aoni/option\"\n")

	for _, imp := range root.Imports {
		if imp.Path == "context" || imp.Path == "fmt" ||
			imp.Path == "encoding/json" || imp.Path == "net/http" ||
			imp.Path == "net/http/httptest" || imp.Path == "strings" ||
			imp.Path == "strconv" || imp.Path == "sync" || imp.Path == "testing" ||
			imp.Path == "time" ||
			imp.Path == "github.com/lemon4ksan/aoni" || imp.Path == "github.com/lemon4ksan/aoni/option" ||
			imp.Path == "github.com/lemon4ksan/aoni/fast" {
			continue
		}

		pkgName := imp.Alias
		if pkgName == "" {
			pkgName = filepath.Base(imp.Path)
		}

		// Only include if referenced in generated mock code
		if !strings.Contains(bodyCode, pkgName+".") {
			continue
		}

		if pkgName != "" && pkgName != filepath.Base(imp.Path) {
			fmt.Fprintf(&buf, "\t%s %q\n", pkgName, imp.Path)
		} else {
			fmt.Fprintf(&buf, "\t%q\n", imp.Path)
		}
	}

	buf.WriteString(")\n\n")
	buf.Write(bodyBuf.Bytes())

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("mock formatting error: %w", err)
	}

	return formatted, nil
}

func emitServiceMock(buf *bytes.Buffer, svc *ir.ServiceIR) error {
	mockServerName := svc.Name + "MockServer"
	clientStructName := lowerFirst(svc.Name) + "Client"

	// 1. Struct Definition
	fmt.Fprintf(buf, "// %s is a virtual in-memory HTTP server for unit testing %s.\n", mockServerName, svc.Name)
	fmt.Fprintf(buf, "type %s struct {\n", mockServerName)
	buf.WriteString("\tserver *httptest.Server\n")
	buf.WriteString("\tmu sync.Mutex\n")
	buf.WriteString("\tcalls map[string]int\n\n")

	// Handler fields
	for _, m := range svc.Methods {
		handlerSig := renderMockHandlerSignature(m)
		fmt.Fprintf(buf, "\ton%s %s\n", m.Name, handlerSig)
	}

	buf.WriteString("}\n\n")

	// 2. Factory Constructor
	fmt.Fprintf(buf, "// New%s spins up an active in-memory test server.\n", mockServerName)
	fmt.Fprintf(buf, "// If t is non-nil, cleanup is automatically registered via t.Cleanup.\n")
	fmt.Fprintf(buf, "func New%s(t testing.TB) *%s {\n", mockServerName, mockServerName)
	fmt.Fprintf(buf, "\tmock := &%s{\n", mockServerName)
	buf.WriteString("\t\tcalls: make(map[string]int),\n")
	buf.WriteString("\t}\n\n")
	buf.WriteString("\tmux := http.NewServeMux()\n")
	buf.WriteString("\tmux.HandleFunc(\"/\", mock.routeRequest)\n")
	buf.WriteString("\tmock.server = httptest.NewServer(mux)\n\n")
	buf.WriteString("\tif t != nil {\n")
	buf.WriteString("\t\tt.Cleanup(mock.Close)\n")
	buf.WriteString("\t}\n\n")
	buf.WriteString("\treturn mock\n")
	buf.WriteString("}\n\n")

	// 3. Server URL
	fmt.Fprintf(buf, "// URL returns the base HTTP address of the virtual test server.\n")
	fmt.Fprintf(buf, "func (m *%s) URL() string {\n", mockServerName)
	buf.WriteString("\tif m.server == nil {\n")
	buf.WriteString("\t\treturn \"\"\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn m.server.URL\n")
	buf.WriteString("}\n\n")

	// 4. Close
	fmt.Fprintf(buf, "// Close shuts down the underlying httptest.Server.\n")
	fmt.Fprintf(buf, "func (m *%s) Close() {\n", mockServerName)
	buf.WriteString("\tif m.server != nil {\n")
	buf.WriteString("\t\tm.server.Close()\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	// 5. Client Factory
	fmt.Fprintf(
		buf,
		"// Client instantiates a pre-configured %s connected directly to this virtual test server.\n",
		svc.Name,
	)
	fmt.Fprintf(buf, "func (m *%s) Client(opts ...aoni.ClientOption) %s {\n", mockServerName, svc.Name)
	buf.WriteString("\tallOpts := append([]aoni.ClientOption{option.WithBaseURL(m.URL())}, opts...)\n")
	buf.WriteString("\tc := aoni.NewClient(fast.NewClient(), allOpts...)\n")
	fmt.Fprintf(buf, "\treturn &%s{\n", clientStructName)
	buf.WriteString("\t\tr: c,\n")
	buf.WriteString("\t}\n")
	buf.WriteString("}\n\n")

	// 6. On<Method> Handlers and Call Counters
	for _, m := range svc.Methods {
		handlerSig := renderMockHandlerSignature(m)
		fmt.Fprintf(buf, "// On%s registers a mock handler for %s.\n", m.Name, m.Name)
		fmt.Fprintf(buf, "func (m *%s) On%s(fn %s) *%s {\n", mockServerName, m.Name, handlerSig, mockServerName)
		buf.WriteString("\tm.mu.Lock()\n")
		buf.WriteString("\tdefer m.mu.Unlock()\n")
		fmt.Fprintf(buf, "\tm.on%s = fn\n", m.Name)
		buf.WriteString("\treturn m\n")
		buf.WriteString("}\n\n")
	}

	// 7. Call Inspector
	fmt.Fprintf(buf, "// Calls returns the number of times a method has been invoked.\n")
	fmt.Fprintf(buf, "func (m *%s) Calls(method string) int {\n", mockServerName)
	buf.WriteString("\tm.mu.Lock()\n")
	buf.WriteString("\tdefer m.mu.Unlock()\n")
	buf.WriteString("\treturn m.calls[method]\n")
	buf.WriteString("}\n\n")

	fmt.Fprintf(buf, "func (m *%s) recordCall(method string) {\n", mockServerName)
	buf.WriteString("\tm.mu.Lock()\n")
	buf.WriteString("\tdefer m.mu.Unlock()\n")
	buf.WriteString("\tm.calls[method]++\n")
	buf.WriteString("}\n\n")

	// 8. Internal Router Dispatcher
	fmt.Fprintf(buf, "func (m *%s) routeRequest(w http.ResponseWriter, r *http.Request) {\n", mockServerName)
	buf.WriteString("\tpath := r.URL.Path\n")
	buf.WriteString("\tmethod := r.Method\n")
	buf.WriteString("\tparts := strings.Split(strings.Trim(path, \"/\"), \"/\")\n")
	buf.WriteString("\t_ = parts\n\n")

	for _, m := range svc.Methods {
		emitMethodRouteMatch(buf, m)
	}

	// Fallback 404
	buf.WriteString(
		"\thttp.Error(w, fmt.Sprintf(\"mock server: unhandled %s %s\", method, path), http.StatusNotFound)\n",
	)
	buf.WriteString("}\n\n")

	return nil
}

func renderMockHandlerSignature(m *ir.MethodIR) string {
	var params []string

	params = append(params, "ctx context.Context")

	for _, p := range m.Params {
		if p.Location == ir.LocContext || p.Location == ir.LocModifiers {
			continue
		}

		params = append(params, fmt.Sprintf("%s %s", p.GoName, p.GoType.Name))
	}

	retType := "any"
	if m.Return != nil && m.Return.SuccessType.Name != "" {
		retType = m.Return.SuccessType.Name
	}

	return fmt.Sprintf("func(%s) (%s, error)", strings.Join(params, ", "), retType)
}

func emitMethodRouteMatch(buf *bytes.Buffer, m *ir.MethodIR) {
	httpVerb := strings.ToUpper(m.HTTPMethod)
	if httpVerb == "" {
		httpVerb = "GET"
	}

	rawPath := ""
	if m.Path != nil {
		rawPath = m.Path.RawTemplate
	}

	cleanPath := strings.Trim(rawPath, "/")
	if cleanPath == "" {
		cleanPath = strings.ToLower(m.Name)
	}

	slashParts := strings.Split(cleanPath, "/")
	if len(slashParts) == 1 && slashParts[0] == "" {
		fmt.Fprintf(buf, "\tif method == %q && (path == %q || path == \"\" || path == \"/\") {\n", httpVerb, rawPath)
	} else {
		var conds []string

		conds = append(conds, fmt.Sprintf("method == %q", httpVerb))

		conds = append(conds, fmt.Sprintf("len(parts) == %d", len(slashParts)))
		for i, sp := range slashParts {
			if !strings.Contains(sp, "{") {
				conds = append(conds, fmt.Sprintf("parts[%d] == %q", i, sp))
			}
		}

		fmt.Fprintf(buf, "\tif %s {\n", strings.Join(conds, " && "))
	}

	fmt.Fprintf(buf, "\t\tm.recordCall(%q)\n", m.Name)
	fmt.Fprintf(buf, "\t\tif m.on%s == nil {\n", m.Name)

	if m.MockFixture != nil && (m.MockFixture.Body != "" || m.MockFixture.StatusCode != 0) {
		ct := m.MockFixture.ContentType
		if ct == "" {
			ct = "application/json"
		}

		fmt.Fprintf(buf, "\t\t\tw.Header().Set(\"Content-Type\", %q)\n", ct)

		for k, v := range m.MockFixture.Headers {
			if strings.EqualFold(k, "content-type") || strings.EqualFold(k, "content-length") {
				continue
			}

			fmt.Fprintf(buf, "\t\t\tw.Header().Set(%q, %q)\n", k, v)
		}

		status := m.MockFixture.StatusCode
		if status == 0 {
			status = 200
		}

		fmt.Fprintf(buf, "\t\t\tw.WriteHeader(%d)\n", status)

		if m.MockFixture.Body != "" {
			fmt.Fprintf(buf, "\t\t\t_, _ = w.Write([]byte(%q))\n", m.MockFixture.Body)
		} else {
			buf.WriteString("\t\t\t_, _ = w.Write([]byte(\"{}\"))\n")
		}

		buf.WriteString("\t\t\treturn\n")
	} else {
		buf.WriteString("\t\t\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
		buf.WriteString("\t\t\tw.WriteHeader(http.StatusOK)\n")
		buf.WriteString("\t\t\t_, _ = w.Write([]byte(\"{}\"))\n")
		buf.WriteString("\t\t\treturn\n")
	}

	buf.WriteString("\t\t}\n\n")

	// Prepare call parameters
	var callArgs []string

	callArgs = append(callArgs, "r.Context()")

	for _, p := range m.Params {
		if p.Location == ir.LocContext || p.Location == ir.LocModifiers {
			continue
		}

		varName := "arg_" + p.GoName

		if p.Location == ir.LocBody || p.Location == ir.LocQueryStruct || p.Location == ir.LocFormFields ||
			strings.HasSuffix(
				p.GoType.Name,
				"Request",
			) || strings.HasSuffix(p.GoType.Name, "Req") || strings.HasSuffix(p.GoType.Name, "Query") {
			fmt.Fprintf(buf, "\t\tvar %s %s\n", varName, p.GoType.Name)
			fmt.Fprintf(buf, "\t\t_ = json.NewDecoder(r.Body).Decode(&%s)\n", varName)
			callArgs = append(callArgs, varName)
		} else {
			// Extract simple string/number parameter
			wireKey := p.WireKey
			if wireKey == "" {
				wireKey = strings.ToLower(p.GoName)
			}

			rawValName := "raw_" + p.GoName

			pathIdx := -1
			if p.Location == ir.LocPath {
				for idx, sp := range slashParts {
					if strings.Contains(sp, p.WireKey) ||
						strings.EqualFold(cleanIdentifier(sp), cleanIdentifier(p.GoName)) ||
						strings.EqualFold(cleanIdentifier(sp), cleanIdentifier(p.WireKey)) {
						pathIdx = idx
						break
					}
				}
			}

			switch {
			case pathIdx != -1:
				fmt.Fprintf(buf, "\t\t%s := parts[%d]\n", rawValName, pathIdx)
			case p.Location == ir.LocFormFields || p.Location == ir.LocMultipartField:
				fmt.Fprintf(buf, "\t\t%s := r.FormValue(%q)\n", rawValName, wireKey)
				fmt.Fprintf(buf, "\t\tif %s == \"\" {\n", rawValName)
				fmt.Fprintf(buf, "\t\t\t%s = r.URL.Query().Get(%q)\n", rawValName, wireKey)
				fmt.Fprintf(buf, "\t\t}\n")
			default:
				fmt.Fprintf(buf, "\t\t%s := r.URL.Query().Get(%q)\n", rawValName, wireKey)
				fmt.Fprintf(buf, "\t\tif %s == \"\" {\n", rawValName)
				fmt.Fprintf(buf, "\t\t\tif len(parts) > 0 {\n\t\t\t\t%s = parts[len(parts)-1]\n\t\t\t}\n", rawValName)
				fmt.Fprintf(buf, "\t\t}\n")
			}

			switch {
			case p.GoType.IsSlice:
				switch {
				case p.Location == ir.LocBody:
					fmt.Fprintf(buf, "\t\tvar %s %s\n", varName, p.GoType.Name)
					fmt.Fprintf(buf, "\t\t_ = json.NewDecoder(r.Body).Decode(&%s)\n", varName)
					callArgs = append(callArgs, varName)
				case p.GoType.Name == "[]string":
					fmt.Fprintf(buf, "\t\tvar %s []string\n", varName)
					fmt.Fprintf(buf, "\t\tif %s != \"\" {\n", rawValName)
					fmt.Fprintf(buf, "\t\t\t%s = strings.Split(%s, \",\")\n", varName, rawValName)
					buf.WriteString("\t\t}\n")

					callArgs = append(callArgs, varName)

				default:
					fmt.Fprintf(buf, "\t\tvar %s %s\n", varName, p.GoType.Name)
					callArgs = append(callArgs, varName)
				}

			case p.GoType.Name == "time.Time" || p.GoType.Name == "Time":
				fmt.Fprintf(buf, "\t\tvar %s time.Time\n", varName)
				fmt.Fprintf(buf, "\t\tif tVal, tErr := time.Parse(time.RFC3339, %s); tErr == nil {\n", rawValName)
				fmt.Fprintf(buf, "\t\t\t%s = tVal\n", varName)
				fmt.Fprintf(buf, "\t\t}\n")

				callArgs = append(callArgs, varName)

			case p.GoType.IsCustomType:
				fmt.Fprintf(buf, "\t\tvar %s %s\n", varName, p.GoType.Name)
				fmt.Fprintf(
					buf,
					"\t\tif _n_%s, _err_%s := strconv.ParseUint(%s, 10, 64); _err_%s == nil {\n",
					p.GoName,
					p.GoName,
					rawValName,
					p.GoName,
				)
				fmt.Fprintf(buf, "\t\t\t%s = %s(_n_%s)\n", varName, p.GoType.Name, p.GoName)
				fmt.Fprintf(
					buf,
					"\t\t} else if _n_%s, _err_%s := strconv.Atoi(%s); _err_%s == nil {\n",
					p.GoName,
					p.GoName,
					rawValName,
					p.GoName,
				)
				fmt.Fprintf(buf, "\t\t\t%s = %s(_n_%s)\n", varName, p.GoType.Name, p.GoName)
				fmt.Fprintf(buf, "\t\t}\n")

				callArgs = append(callArgs, varName)

			default:
				switch p.GoType.Name {
				case "int":
					fmt.Fprintf(buf, "\t\t%s, _ := strconv.Atoi(%s)\n", varName, rawValName)
					callArgs = append(callArgs, varName)
				case "int32":
					fmt.Fprintf(buf, "\t\tv32_%s, _ := strconv.ParseInt(%s, 10, 32)\n", p.GoName, rawValName)
					fmt.Fprintf(buf, "\t\t%s := int32(v32_%s)\n", varName, p.GoName)
					callArgs = append(callArgs, varName)
				case "int64":
					fmt.Fprintf(buf, "\t\t%s, _ := strconv.ParseInt(%s, 10, 64)\n", varName, rawValName)
					callArgs = append(callArgs, varName)
				case "uint":
					fmt.Fprintf(buf, "\t\tvu_%s, _ := strconv.ParseUint(%s, 10, 64)\n", p.GoName, rawValName)
					fmt.Fprintf(buf, "\t\t%s := uint(vu_%s)\n", varName, p.GoName)
					callArgs = append(callArgs, varName)
				case "uint32":
					fmt.Fprintf(buf, "\t\tvu32_%s, _ := strconv.ParseUint(%s, 10, 32)\n", p.GoName, rawValName)
					fmt.Fprintf(buf, "\t\t%s := uint32(vu32_%s)\n", varName, p.GoName)
					callArgs = append(callArgs, varName)
				case "uint64":
					fmt.Fprintf(buf, "\t\t%s, _ := strconv.ParseUint(%s, 10, 64)\n", varName, rawValName)
					callArgs = append(callArgs, varName)
				case "float64":
					fmt.Fprintf(buf, "\t\t%s, _ := strconv.ParseFloat(%s, 64)\n", varName, rawValName)
					callArgs = append(callArgs, varName)
				case "float32":
					fmt.Fprintf(buf, "\t\tvf32_%s, _ := strconv.ParseFloat(%s, 32)\n", p.GoName, rawValName)
					fmt.Fprintf(buf, "\t\t%s := float32(vf32_%s)\n", varName, p.GoName)
					callArgs = append(callArgs, varName)
				case "bool":
					fmt.Fprintf(buf, "\t\t%s, _ := strconv.ParseBool(%s)\n", varName, rawValName)
					callArgs = append(callArgs, varName)
				default:
					callArgs = append(callArgs, rawValName)
				}
			}
		}
	}

	fmt.Fprintf(buf, "\t\tres, err := m.on%s(%s)\n", m.Name, strings.Join(callArgs, ", "))
	buf.WriteString("\t\tif err != nil {\n")
	buf.WriteString("\t\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n")
	buf.WriteString("\t\t\treturn\n")
	buf.WriteString("\t\t}\n\n")
	buf.WriteString("\t\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
	buf.WriteString("\t\t_ = json.NewEncoder(w).Encode(res)\n")
	buf.WriteString("\t\treturn\n")
	buf.WriteString("\t}\n\n")
}
