// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package project_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/lemon4ksan/foundation/testing/require"

	"github.com/lemon4ksan/vortex/pkg/project"
)

func TestProject_FindRootAndAutoDiscover(t *testing.T) {
	tempDir := t.TempDir()

	// 1. Create a dummy go.mod
	goModPath := filepath.Join(tempDir, "go.mod")
	err := os.WriteFile(goModPath, []byte("module testmod\n\ngo 1.25.4\n"), 0o600)
	require.NoError(t, err)

	// 2. Create nested service folder
	serviceDir := filepath.Join(tempDir, "pkg", "services", "user")
	err = os.MkdirAll(serviceDir, 0o750)
	require.NoError(t, err)

	apiFile := filepath.Join(serviceDir, "api.go")
	apiSrc := `package user

import (
	"context"
	"github.com/lemon4ksan/aoni"
)

// @aoni:service
// @version "v1.0.0"
type UserAPI interface {
	// @get "users/{id}"
	GetUser(ctx context.Context, id string, mods ...aoni.RequestModifier) (*UserDTO, error)
}

// @aoni:dto
type UserDTO struct {
	ID string
}
`
	err = os.WriteFile(apiFile, []byte(apiSrc), 0o600)
	require.NoError(t, err)

	// 3. Test FindRoot from nested subfolder
	subDir := filepath.Join(serviceDir, "nested", "deeper")
	err = os.MkdirAll(subDir, 0o750)
	require.NoError(t, err)

	discoveredRoot, cfgPath, err := project.FindRoot(subDir)
	require.NoError(t, err)
	require.Equal(t, tempDir, discoveredRoot)
	require.Empty(t, cfgPath) // No .vortex.yml yet

	// 4. Test AutoDiscover
	cfg, err := project.AutoDiscover(tempDir)
	require.NoError(t, err)
	require.Equal(t, tempDir, cfg.RootDir)
	require.Len(t, cfg.Contracts, 1)
	require.Equal(t, "UserAPI", cfg.Contracts[0].Name)
	require.Equal(t, "user", cfg.Contracts[0].Package)

	// 5. Test Init creates .vortex.yml
	createdCfg, err := project.Init(tempDir, false)
	require.NoError(t, err)
	require.FileExists(t, filepath.Join(tempDir, ".vortex.yml"))
	require.Len(t, createdCfg.Contracts, 1)

	// 6. Test FindRoot now finds explicit .vortex.yml
	discoveredRoot2, cfgPath2, err := project.FindRoot(subDir)
	require.NoError(t, err)
	require.Equal(t, tempDir, discoveredRoot2)
	require.Equal(t, filepath.Join(tempDir, ".vortex.yml"), cfgPath2)

	// 7. Test Load parses .vortex.yml
	loadedCfg, err := project.Load(subDir)
	require.NoError(t, err)
	require.Equal(t, tempDir, loadedCfg.RootDir)
	require.Len(t, loadedCfg.Contracts, 1)
	require.Equal(t, "UserAPI", loadedCfg.Contracts[0].Name)
}

func TestProject_StatusEngine(t *testing.T) {
	tempDir := t.TempDir()

	serviceDir := filepath.Join(tempDir, "pkg", "user")
	err := os.MkdirAll(serviceDir, 0o750)
	require.NoError(t, err)

	apiFile := filepath.Join(serviceDir, "api.go")
	apiSrc := `package user

import (
	"context"
	"github.com/lemon4ksan/aoni"
)

// @aoni:service
type API interface {
	// @get "me"
	GetMe(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error)
}
`
	err = os.WriteFile(apiFile, []byte(apiSrc), 0o600)
	require.NoError(t, err)

	cfg := &project.Config{
		RootDir: tempDir,
		Contracts: []project.ContractConfig{
			{
				Name:    "API",
				Package: "user",
				File:    "pkg/user/api.go",
				Gen:     "pkg/user/api.gen.go",
			},
		},
	}

	engine := project.NewStatusEngine()

	// 1. First inspection: api.gen.go is missing -> Stale
	report := engine.Inspect(cfg, cfg.Contracts)
	require.Len(t, report.Contracts, 1)
	require.True(t, report.Contracts[0].IsGenStale)
	require.Equal(t, 1, report.StaleCount())
	require.True(t, report.HasIssues())
	require.Len(t, report.NextActions, 1)

	// 2. Create api.gen.go
	genFile := filepath.Join(serviceDir, "api.gen.go")
	err = os.WriteFile(genFile, []byte("// Code generated by vortex. DO NOT EDIT.\npackage user\n"), 0o600)
	require.NoError(t, err)

	// 3. Second inspection: up-to-date!
	report2 := engine.Inspect(cfg, cfg.Contracts)
	require.False(t, report2.Contracts[0].IsGenStale)
	require.Equal(t, 0, report2.StaleCount())
	require.False(t, report2.HasIssues())

	// 4. Test Render output
	rendered := report2.Render(false)
	require.Contains(t, rendered, "API")
	require.Contains(t, rendered, "100% in sync")
	require.Contains(t, rendered, "All systems nominal")

	// 5. Test JSON rendering
	jsonData, err := report2.RenderJSON()
	require.NoError(t, err)
	require.Contains(t, string(jsonData), "\"total_methods\": 1")
}

func TestProject_IgnoreRules(t *testing.T) {
	cfg := &project.Config{
		Ignore: []string{"sensitive-query-param", "param-lifting"},
		Lint: project.LintConfig{
			Ignore:  []string{"missing-context"},
			Disable: []string{"S001"},
		},
	}

	rules := cfg.AllIgnoredRules()
	require.Contains(t, rules, "sensitive-query-param")
	require.Contains(t, rules, "param-lifting")
	require.Contains(t, rules, "missing-context")
	require.Contains(t, rules, "S001")
	require.Len(t, rules, 4)
}

func TestProject_EnsureGitignore(t *testing.T) {
	tempDir := t.TempDir()

	// 1. First run creates .gitignore
	updated, err := project.EnsureGitignore(tempDir)
	require.NoError(t, err)
	require.True(t, updated)

	giFile := filepath.Join(tempDir, ".gitignore")
	content, err := os.ReadFile(giFile)
	require.NoError(t, err)
	require.Contains(t, string(content), "*_mock.gen.go")
	require.Contains(t, string(content), "*_harness.gen.go")
	require.Contains(t, string(content), ".vortex/")

	// 2. Second run is a no-op
	updated2, err := project.EnsureGitignore(tempDir)
	require.NoError(t, err)
	require.False(t, updated2)

	// 3. Existing .gitignore with other contents gets appended
	tempDir2 := t.TempDir()
	giFile2 := filepath.Join(tempDir2, ".gitignore")
	err = os.WriteFile(giFile2, []byte("node_modules/\n*.log\n"), 0o600)
	require.NoError(t, err)

	updated3, err := project.EnsureGitignore(tempDir2)
	require.NoError(t, err)
	require.True(t, updated3)

	content2, err := os.ReadFile(giFile2)
	require.NoError(t, err)
	require.Contains(t, string(content2), "node_modules/")
	require.Contains(t, string(content2), "*_mock.gen.go")
}

func TestProject_MultiServiceConsolidation(t *testing.T) {
	tempDir := t.TempDir()
	serviceDir := filepath.Join(tempDir, "pkg", "steam", "webapi")
	require.NoError(t, os.MkdirAll(serviceDir, 0o750))

	apiFile := filepath.Join(serviceDir, "api.go")
	apiSrc := `package webapi

import (
	"context"
	"github.com/lemon4ksan/aoni"
)

// @aoni:service
type CSGOPlayers730 interface {
	// @get "IGetCommunityBadgeProgress/v1"
	GetProgress(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error)
}

// @aoni:service
type DOTA2Match570 interface {
	// @get "GetMatchHistory/v1"
	GetMatch(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error)
}
`
	require.NoError(t, os.WriteFile(apiFile, []byte(apiSrc), 0o600))

	cfg, err := project.AutoDiscover(tempDir)
	require.NoError(t, err)
	// Must consolidate into exactly 1 contract entry
	require.Len(t, cfg.Contracts, 1)
	require.Equal(t, "Webapi", cfg.Contracts[0].Name)
	cfg.Normalize()
	require.Equal(t, "webapi", cfg.Contracts[0].Package)
}

func TestProject_AutoDiscover_Exclude(t *testing.T) {
	tempDir := t.TempDir()

	p1 := filepath.Join(tempDir, "pkg", "api")
	p2 := filepath.Join(tempDir, "internal", "legacy")

	require.NoError(t, os.MkdirAll(p1, 0o750))
	require.NoError(t, os.MkdirAll(p2, 0o750))

	src := `package testpkg
import (
	"context"
	"github.com/lemon4ksan/aoni"
)
// @aoni:service
type API interface {
	// @get "test"
	Get(ctx context.Context, mods ...aoni.RequestModifier) (map[string]any, error)
}
`
	require.NoError(t, os.WriteFile(filepath.Join(p1, "api.go"), []byte(src), 0o600))
	require.NoError(t, os.WriteFile(filepath.Join(p2, "api.go"), []byte(src), 0o600))

	cfg, err := project.AutoDiscover(tempDir, project.AutoDiscoverOptions{
		Exclude: []string{"internal/**"},
	})
	require.NoError(t, err)
	require.Len(t, cfg.Contracts, 1)
	require.Equal(t, "pkg/api/api.go", cfg.Contracts[0].File)
}

func TestProject_EnsureGitattributes(t *testing.T) {
	tempDir := t.TempDir()

	// 1. First run creates .gitattributes
	updated, err := project.EnsureGitattributes(tempDir)
	require.NoError(t, err)
	require.True(t, updated)

	gaFile := filepath.Join(tempDir, ".gitattributes")
	content, err := os.ReadFile(gaFile)
	require.NoError(t, err)
	require.Contains(t, string(content), "linguist-generated=true")
	require.Contains(t, string(content), "*.gen.go")
	require.Contains(t, string(content), "eol=lf")

	// 2. Second run is a no-op
	updated2, err := project.EnsureGitattributes(tempDir)
	require.NoError(t, err)
	require.False(t, updated2)

	// 3. Existing .gitattributes with custom rules gets appended
	tempDir2 := t.TempDir()
	gaFile2 := filepath.Join(tempDir2, ".gitattributes")
	err = os.WriteFile(gaFile2, []byte("*.md text\n*.png binary\n"), 0o600)
	require.NoError(t, err)

	updated3, err := project.EnsureGitattributes(tempDir2)
	require.NoError(t, err)
	require.True(t, updated3)

	content2, err := os.ReadFile(gaFile2)
	require.NoError(t, err)
	require.Contains(t, string(content2), "*.png binary")
	require.Contains(t, string(content2), "linguist-generated=true")
}

func TestProject_StatusRenderAlignment(t *testing.T) {
	report := &project.StatusReport{
		WorkspaceRoot: "D:/CodingProjects/g-man",
		TotalMethods:  268,
		TotalDTOs:     55,
		Contracts: []project.ContractStatus{
			{
				Name:         "WebAPI",
				File:         "pkg/steam/webapi/api.go",
				MethodsCount: 169,
				DTOsCount:    44,
			},
			{
				Name:         "Inventory",
				File:         "pkg/steam/community/inventory/api.go",
				MethodsCount: 3,
				DTOsCount:    2,
			},
			{
				Name:         "Market",
				File:         "pkg/steam/community/market/api.go",
				MethodsCount: 17,
			},
			{
				Name:           "Notifications",
				File:           "pkg/steam/sys/notifications/api.go",
				MethodsCount:   10,
				IsGenStale:     true,
				GenStaleReason: "api.gen.go is STALE",
			},
		},
	}

	rendered := report.Render(false)

	// Check headers and summary
	require.Contains(t, rendered, "◆ Vortex API Guardian")
	require.Contains(t, rendered, "Workspace: D:/CodingProjects/g-man (4 services, 268 methods)")
	require.Contains(t, rendered, "● Contracts & Generated Code:")

	// Check rows
	require.Contains(t, rendered, "WebAPI")
	require.Contains(t, rendered, "(pkg/steam/webapi)")
	require.Contains(t, rendered, "169 methods, 44 DTOs")
	require.Contains(t, rendered, "100% in sync")

	require.Contains(t, rendered, "Notifications")
	require.Contains(t, rendered, "(pkg/steam/sys/notifications)")
	require.Contains(t, rendered, "10 methods")
	require.Contains(t, rendered, "api.gen.go is STALE")

	// Check color rendering
	colored := report.Render(true)
	require.Contains(t, colored, "WebAPI")
	require.Contains(t, colored, "Notifications")
}
