// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package ast provides a public, programmatic Abstract Syntax Tree (AST) for constructing,
// inspecting, transforming, and rendering Aoni declarative API contracts.
//
// # What is the AST Package? (The "Code Constructor" Paradigm)
//
// When writing code generators, OpenAPI/Swagger importers, or microservice SDK builders, developers
// traditionally concatenate raw strings using fmt.Sprintf or text templates. This approach is fragile:
// it easily produces syntax errors, broken struct tags, inconsistent indentation, and unmaintainable logic.
//
// The ast package solves this by treating Aoni Go contracts as a structured, in-memory tree of nodes
// ([File], [Service], [Method], [Struct], [Field]). You build contracts programmatically via fluent builders,
// and render them into standard, gofmt-formatted Go source code with a single call to [Format] or [WriteFile].
//
// # Core AST Building Blocks
//
//   - [File] represents a root Go file containing package metadata, imports, services, and DTOs.
//   - [Service] defines an API service interface with protocol tags, base URLs, and casing rules.
//   - [Method] defines an RPC/REST endpoint method with parameters, models, and @unwrap directives.
//   - [Struct] and [Field] model typed request/response payload DTOs with json/url struct tags.
//   - [Tuple] models positional Protobuf / JSPB sparse index contracts.
//   - [Union] models polymorphic discriminated union types.
//   - [Bitpack] models high-density bitfield structs.
//
// # Quick Start: Generating an API Client in 5 Steps
//
// The following snippet demonstrates building an API contract for GitHub:
//
//	// 1. Create a root AST file
//	file := ast.NewFile("github")
//
//	// 2. Define the service interface
//	svc := file.NewService("GitHubAPI").
//	    WithBaseURL("https://api.github.com").
//	    WithEngine(ast.EngineFast).
//	    WithDoc("GitHubAPI provides client bindings for GitHub REST API.")
//
//	// 3. Add an endpoint method
//	svc.NewMethod("GetUser", "GET", "users/{username}").
//	    WithDoc("GetUser retrieves public user profile information.").
//	    AddParam("username", "string").
//	    WithResponse("*User")
//
//	// 4. Define the returned DTO struct
//	user := file.NewStruct("User").WithDoc("User represents a GitHub user account.")
//	user.AddField("ID", "int64", "id", true)
//	user.AddField("Login", "string", "login", true)
//	user.AddField("Bio", "*string", "bio", false)
//
//	// 5. Render into formatted Go source code
//	code, err := ast.Format(file)
//	// Or write directly to disk:
//	err = ast.WriteFile("github_client.gen.go", file)
//
// # Resulting Generated Go Code Output
//
// Calling [Format] on the file above produces:
//
//	// Code generated by Aoni AST Builder. DO NOT EDIT.
//
//	package github
//
//	import (
//	    "context"
//	    "github.com/lemon4ksan/aoni"
//	)
//
//	// GitHubAPI provides client bindings for GitHub REST API.
//	//
//	// @aoni:service casing=snake_case
//	// @engine fast
//	// @base_url "https://api.github.com"
//	type GitHubAPI interface {
//	    // GetUser retrieves public user profile information.
//	    //
//	    // @get "users/{username}"
//	    GetUser(ctx context.Context, username string, mods ...aoni.RequestModifier) (*User, error)
//	}
//
//	// User represents a GitHub user account.
//	//
//	// @aoni:dto omitempty=true
//	type User struct {
//	    ID    int64   `json:"id"`
//	    Login string  `json:"login"`
//	    Bio   *string `json:"bio,omitempty"`
//	}
//
// # Programmatic Inspection & AST Querying
//
// AST nodes support type-safe lookup methods backed by [github.com/lemon4ksan/foundation/generic]:
//
//	// Standard (T, bool) idiom:
//	if svc, ok := file.FindService("GitHubAPI"); ok {
//	    if method, found := svc.FindMethod("GetUser"); found {
//	        fmt.Printf("Found endpoint: %s %s\n", method.HTTPMethod, method.Path)
//	    }
//	}
//
//	// Functional Optional style:
//	if svc, ok := file.FindServiceOptional("GitHubAPI").Value(); ok {
//	    ...
//	}
package ast
