// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ast

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/lemon4ksan/foundation/generic"
)

// Format renders and formats the AST file as standard Go code.
func Format(f *File) ([]byte, error) {
	var buf bytes.Buffer
	if err := Print(&buf, f); err != nil {
		return nil, err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Return unformatted source with syntax error for debugging
		return buf.Bytes(), fmt.Errorf("formatting go code: %w\nSource:\n%s", err, buf.String())
	}

	return formatted, nil
}

// WriteFile writes the formatted AST Go code to disk.
func WriteFile(filename string, f *File) error {
	data, err := Format(f)
	if err != nil {
		return err
	}

	if dir := filepath.Dir(filename); dir != "" && dir != "." {
		if mkErr := os.MkdirAll(dir, 0o755); mkErr != nil {
			return fmt.Errorf("creating directory %s: %w", dir, mkErr)
		}
	}

	return os.WriteFile(filename, data, 0o644)
}

// Print renders the unformatted AST into an io.Writer.
func Print(w io.Writer, f *File) error {
	fmt.Fprintf(w, "// Code generated by Aoni AST Builder. DO NOT EDIT.\n\n")
	fmt.Fprintf(w, "package %s\n\n", f.PackageName)

	if len(f.Doc) > 0 {
		renderWrappedDoc(w, f.Doc, "", "", "", f.MaxLen)
		fmt.Fprintf(w, "\n")
	}

	if len(f.Imports) > 0 {
		fmt.Fprintf(w, "import (\n")

		for _, imp := range f.Imports {
			if imp.Alias != "" {
				fmt.Fprintf(w, "\t%s %q\n", imp.Alias, imp.Path)
			} else {
				fmt.Fprintf(w, "\t%q\n", imp.Path)
			}
		}

		fmt.Fprintf(w, ")\n\n")
	}

	// Render Services
	for _, svc := range f.Services {
		renderWrappedDoc(w, svc.Doc, svc.Name, "provides client bindings", "", f.MaxLen)
		fmt.Fprintf(w, "//\n")
		fmt.Fprintf(w, "// @aoni:service casing=%s\n", generic.Coalesce(string(svc.Casing), "snake_case"))

		if svc.Engine != "" && svc.Engine != EngineNetHTTP {
			fmt.Fprintf(w, "// @engine %s\n", svc.Engine)
		}

		if svc.BaseURL != "" {
			fmt.Fprintf(w, "// @base_url %q\n", svc.BaseURL)
		}

		if svc.UnwrapField != "" {
			fmt.Fprintf(w, "// @unwrap %q\n", svc.UnwrapField)
		}

		for _, h := range svc.Headers {
			fmt.Fprintf(w, "// @header %q %q\n", h.Name, h.Value)
		}

		fmt.Fprintf(w, "type %s interface {\n", svc.Name)

		for _, m := range svc.Methods {
			renderMethod(w, m, f.MaxLen)
		}

		fmt.Fprintf(w, "}\n\n")
	}

	// Render Structs
	for _, st := range f.Structs {
		renderWrappedDoc(w, st.Doc, st.Name, "represents a data transfer object", "", f.MaxLen)

		if st.Omitempty {
			fmt.Fprintf(w, "//\n// @aoni:dto omitempty=true\n")
		}

		fmt.Fprintf(w, "type %s struct {\n", st.Name)

		for _, fld := range st.Fields {
			renderField(w, fld, f.MaxLen)
		}

		fmt.Fprintf(w, "}\n\n")
	}

	return nil
}

func renderMethod(w io.Writer, m *Method, maxLen int) {
	if maxLen <= 0 {
		maxLen = 120
	}

	renderWrappedDoc(w, m.Doc, m.Name, "calls "+m.Path, "\t", maxLen)
	fmt.Fprintf(w, "\t//\n")

	httpMethod := generic.Coalesce(strings.ToLower(m.HTTPMethod), "get")
	fmt.Fprintf(w, "\t// @%s %q\n", httpMethod, m.Path)

	if m.Form {
		fmt.Fprintf(w, "\t// @form\n")
	}

	if m.UnwrapField != "" {
		fmt.Fprintf(w, "\t// @unwrap %q\n", m.UnwrapField)
	}

	var reqPart string
	if len(m.Parameters) > 0 {
		parts := generic.Map(m.Parameters, func(p Parameter) string {
			return fmt.Sprintf("%s %s", p.Name, p.Type)
		})
		reqPart = strings.Join(parts, ", ") + ", "
	} else if m.RequestModel != "" {
		reqType := m.RequestModel
		if !strings.HasPrefix(reqType, "*") && !isPrimitiveOrSlice(reqType) {
			reqType = "*" + reqType
		}

		reqPart = fmt.Sprintf("req %s, ", reqType)
	}

	respType := generic.Coalesce(m.ResponseModel, "any")
	singleLine := fmt.Sprintf(
		"\t%s(ctx context.Context, %smods ...aoni.RequestModifier) (%s, error)",
		m.Name, reqPart, respType,
	)

	if len(singleLine) > maxLen && (len(m.Parameters) > 0 || m.RequestModel != "") {
		// Multi-line signature
		fmt.Fprintf(w, "\t%s(\n", m.Name)
		fmt.Fprintf(w, "\t\tctx context.Context,\n")

		if len(m.Parameters) > 0 {
			for _, p := range m.Parameters {
				fmt.Fprintf(w, "\t\t%s %s,\n", p.Name, p.Type)
			}
		} else if m.RequestModel != "" {
			reqType := m.RequestModel
			if !strings.HasPrefix(reqType, "*") && !isPrimitiveOrSlice(reqType) {
				reqType = "*" + reqType
			}

			fmt.Fprintf(w, "\t\treq %s,\n", reqType)
		}

		fmt.Fprintf(w, "\t\tmods ...aoni.RequestModifier,\n")
		fmt.Fprintf(w, "\t) (%s, error)\n\n", respType)
	} else {
		fmt.Fprintf(w, "%s\n\n", singleLine)
	}
}

func renderField(w io.Writer, f *Field, maxLen int) {
	if len(f.Doc) > 0 {
		renderWrappedDoc(w, f.Doc, "", "", "\t", maxLen)
	}

	tagParts := []string{}
	if f.QueryName != "" {
		omit := generic.Ternary(f.Required, "", ",omitempty")
		tagParts = append(tagParts, fmt.Sprintf("query:%q", f.QueryName+omit))
	}

	if f.JSONName != "" {
		omit := generic.Ternary(f.Required, "", ",omitempty")
		tagParts = append(tagParts, fmt.Sprintf("json:%q", f.JSONName+omit))
	}

	if f.URLName != "" {
		omit := generic.Ternary(f.Required, "", ",omitempty")
		tagParts = append(tagParts, fmt.Sprintf("url:%q", f.URLName+omit))
	}

	if f.AoniTag != "" {
		tagParts = append(tagParts, fmt.Sprintf("aoni:%q", f.AoniTag))
	}

	if f.CustomTags != "" {
		tagParts = append(tagParts, f.CustomTags)
	}

	var tagStr string
	if len(tagParts) > 0 {
		tagStr = fmt.Sprintf(" `%s`", strings.Join(tagParts, " "))
	}

	fmt.Fprintf(w, "\t%s %s%s\n", f.Name, f.Type, tagStr)
}

func renderWrappedDoc(w io.Writer, doc []string, defaultName, defaultDesc, indent string, maxLen int) {
	if maxLen <= 0 {
		maxLen = 120
	}

	if len(doc) == 0 {
		if defaultName != "" && defaultDesc != "" {
			fmt.Fprintf(w, "%s// %s %s.\n", indent, defaultName, defaultDesc)
		}

		return
	}

	prefixLen := len(indent) + 3 // indent + "// "
	availableWidth := max(maxLen-prefixLen, 40)

	for _, rawLine := range doc {
		rawLine = strings.TrimSpace(rawLine)
		if rawLine == "" {
			fmt.Fprintf(w, "%s//\n", indent)
			continue
		}

		// Keep special directive annotations untruncated
		if isAoniDirective(rawLine) {
			fmt.Fprintf(w, "%s// %s\n", indent, rawLine)
			continue
		}

		// If line fits within maxLen, print directly
		if len(rawLine) <= availableWidth {
			printCommentLine(w, indent, rawLine)
			continue
		}

		// Wrap long text paragraph across word boundaries without slice allocation
		remaining := rawLine

		var current strings.Builder

		for len(remaining) > 0 {
			remaining = strings.TrimLeft(remaining, " \t")
			if len(remaining) == 0 {
				break
			}

			idx := strings.IndexAny(remaining, " \t")

			var word string
			if idx == -1 {
				word = remaining
				remaining = ""
			} else {
				word = remaining[:idx]
				remaining = remaining[idx:]
			}

			switch {
			case current.Len() == 0:
				current.WriteString(word)
			case current.Len()+1+len(word) <= availableWidth:
				current.WriteByte(' ')
				current.WriteString(word)
			default:
				printCommentLine(w, indent, current.String())
				current.Reset()
				current.WriteString(word)
			}
		}

		if current.Len() > 0 {
			printCommentLine(w, indent, current.String())
		}
	}
}

func printCommentLine(w io.Writer, indent, line string) {
	line = strings.TrimSpace(line)
	if strings.HasPrefix(line, "@") && !isAoniDirective(line) {
		fmt.Fprintf(w, "%s// \\%s\n", indent, line)
	} else {
		fmt.Fprintf(w, "%s// %s\n", indent, line)
	}
}

var aoniDirectivePrefixes = [...]string{
	"@aoni:", "@get", "@post", "@put", "@delete", "@patch", "@head", "@options",
	"@ws", "@sse", "@event", "@ws:emit", "@header", "@query", "@form", "@unwrap",
	"@engine", "@base_url", "@retry", "@cache", "@timeout", "@since", "@deprecated",
	"@mirror", "@dto", "@service", "@tuple", "@inject", "@referer", "@preset", "@call",
	"@return", "@body", "@status", "@check", "@field", "@cookie",
}

func isAoniDirective(s string) bool {
	s = strings.TrimSpace(s)
	if !strings.HasPrefix(s, "@") {
		return false
	}

	return generic.Any(aoniDirectivePrefixes[:], func(p string) bool {
		return strings.HasPrefix(s, p)
	})
}

func isPrimitiveOrSlice(t string) bool {
	return strings.HasPrefix(t, "[]") || strings.HasPrefix(t, "map[") ||
		t == "string" || t == "int" || t == "int64" || t == "bool" || t == "float64" || t == "any"
}
