// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pipeline

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"

	"github.com/lemon4ksan/foundation/generic"

	"github.com/lemon4ksan/vortex/pkg/builder"
	"github.com/lemon4ksan/vortex/pkg/cache"
	"github.com/lemon4ksan/vortex/pkg/project"
)

// TrafficPipeline manages traffic caching, credential harvesting into vault, and .env generation.
type TrafficPipeline struct {
	RootDir string
	Config  *project.Config
}

// NewTrafficPipeline initializes a traffic pipeline for the workspace.
func NewTrafficPipeline(rootDir string) (*TrafficPipeline, error) {
	if rootDir == "" {
		cwd, err := os.Getwd()
		if err != nil {
			cwd = "."
		}

		discovered, _, _ := project.FindRoot(cwd)
		rootDir = discovered
	}

	cfg, _ := project.Load(rootDir)

	return &TrafficPipeline{
		RootDir: rootDir,
		Config:  cfg,
	}, nil
}

// IngestHAR stores a HAR capture in .vortex/cache and extracts credentials into the secrets vault.
func (t *TrafficPipeline) IngestHAR(
	harPath string,
	data []byte,
	move, sanitize bool,
) (*cache.TrafficEntry, map[string]cache.SecretEntry, error) {
	if len(data) == 0 {
		var err error

		data, err = os.ReadFile(harPath)
		if err != nil {
			return nil, nil, fmt.Errorf("reading HAR file %s: %w", harPath, err)
		}
	}

	entry, secrets, err := cache.StoreTraffic(t.RootDir, harPath, data, move, sanitize)
	if err != nil {
		return nil, nil, fmt.Errorf("storing traffic: %w", err)
	}

	if len(secrets) > 0 {
		vault, vaultPath, _ := cache.LoadSecrets(t.RootDir)
		for k, s := range secrets {
			vault.SetWithTarget(k, s.Value, entry.ID, s.Header, s.Query, s.Cookie)
		}

		_ = vault.Save(vaultPath)
	}

	return entry, secrets, nil
}

// FillEnv scans contract files for ${VAR_NAME} placeholders and outputs a populated .env file.
func (t *TrafficPipeline) FillEnv(targetFiles []string, outFile string, fillFromVault bool) (int, error) {
	if len(targetFiles) == 0 {
		targetFiles = builder.CollectInputFiles(t.RootDir, []string{"./..."}, builder.CollectOptions{})
	}

	if len(targetFiles) == 0 {
		return 0, errors.New("no contract files found to extract environment variables")
	}

	varRegex := regexp.MustCompile(`\$\{([a-zA-Z0-9_]+)\}`)
	varMap := make(map[string][]string)

	for _, fPath := range targetFiles {
		content, err := os.ReadFile(fPath)
		if err != nil {
			continue
		}

		relPath := fPath
		if t.RootDir != "" && filepath.IsAbs(fPath) {
			if rp, rErr := filepath.Rel(t.RootDir, fPath); rErr == nil {
				relPath = rp
			}
		}

		matches := varRegex.FindAllStringSubmatch(string(content), -1)
		for _, m := range matches {
			if len(m) > 1 {
				varName := m[1]

				already := false
				for _, o := range varMap[varName] {
					if o == relPath {
						already = true
						break
					}
				}

				if !already {
					varMap[varName] = append(varMap[varName], relPath)
				}
			}
		}
	}

	var vault *cache.SecretsVault
	if fillFromVault {
		v, _, _ := cache.LoadSecrets(t.RootDir)
		vault = v
	}

	varNames := generic.Keys(varMap)
	slices.Sort(varNames)

	var sb strings.Builder
	sb.WriteString("# =============================================================================\n")
	sb.WriteString("# Environment & Security Credentials (Generated by Vortex)\n")
	sb.WriteString("# =============================================================================\n\n")

	for _, name := range varNames {
		origins := varMap[name]
		if len(origins) > 0 {
			fmt.Fprintf(&sb, "# Required by: %s\n", strings.Join(origins, ", "))
		}

		val := ""
		if vault != nil {
			if sec, ok := vault.Get(name); ok {
				val = sec
			}
		}

		fmt.Fprintf(&sb, "%s=%s\n\n", name, val)
	}

	if outFile == "-" {
		fmt.Print(sb.String())
		return len(varNames), nil
	}

	if outFile == "" {
		outFile = ".env.example"
	}

	targetOut := outFile
	if !filepath.IsAbs(targetOut) && t.RootDir != "" {
		targetOut = filepath.Join(t.RootDir, targetOut)
	}

	if err := os.WriteFile(targetOut, []byte(sb.String()), 0o600); err != nil {
		return 0, fmt.Errorf("writing env file %s: %w", targetOut, err)
	}

	return len(varNames), nil
}
